---
title: "aula3 - visualização de dados usando o ggplot2"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```


```{r}
setwd("C:/Users/barba/Desktop/ProgramacaoFuncional_Geologia/ProgramacaoFuncional_Geologia/")

dados <- read.csv("geoquim_granite.csv", header = TRUE, sep = ";") %>% 
  as_tibble()

dados
```


# Box plot

```{r}
library(viridis)

dados %>% 
  dplyr::select(TiO2, Tectonic_setting) %>% 
  ggplot(aes(x = TiO2, y = Tectonic_setting, fill = Tectonic_setting)) +
  geom_boxplot() +
  stat_summary(color = "red") +
  scale_fill_viridis(discrete = TRUE, option = "B") +
  theme_bw()

# theme_set(theme_bw() +
#             theme(legend.position = "bottom",
#                   aspect.ratio = 1))
```


# Violine

```{r}
dados %>% 
  ggplot(aes(x = TiO2, y = Tectonic_setting, fill = Tectonic_setting)) +
  geom_violin() +
  stat_summary(color = "red") +
  theme_bw()
```


# Density plot

```{r}
dados %>% 
  ggplot(aes(x = Ce, group = Group, fill = Group)) +
  geom_density(adjust = 1.5) +
  theme(legend.position = "bottom")
```


# Histograma

```{r}
dados %>% 
  filter(Tectonic_setting == "OROGENIC BELT") %>% 
  ggplot(aes(x = Cs)) +
  geom_histogram(color = "white") +
  scale_x_log10()
#distribuição normal?


dados %>% 
  ggplot(aes(x = Ni, fill = Group)) +
  geom_histogram(color = "white", alpha = 0.8) +
  scale_x_log10() +
  facet_wrap(~Group) +
  theme_bw()



dados %>% 
  filter(Tectonic_setting == "OROGENIC BELT") %>% 
  rstatix::shapiro_test(Cs)
#hipótese nula: os dados seguem uma distribuição normal
#valor de p < 0.05 rejeita a hipótese nula, ou seja, os dados não possuem distribuição normal

dados %>% 
  filter(Tectonic_setting == "OROGENIC BELT") %>% 
  mutate(Cs = log(Cs)) %>% #transforma a distribuição dos dados - de não normal p/ normal
  rstatix::shapiro_test(Cs)
```


# Scatter plot()

```{r}
library(ggpubr)

dados %>%
  filter(Group == "1- CPG & MPG") %>% 
  ggplot(aes(x = SiO2, y = MgO, color = SubGroup)) +
  geom_point(alpha = 0.7, size = 2, aes(shape = SubGroup)) +
  geom_smooth(method = "lm", se = TRUE) +
  stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")),
           method = "spearman",
           label.x.npc = "left",
           label.y.npc = "bottom") +
  scale_y_log10() +
  theme(legend.position = "bottom") +
  scale_fill_viridis(discrete = TRUE)

# Reprodução de Bonin et al. (2020)
dados %>% 
  mutate(Q = SiO2/3 - (K2O + Na2O + 2*(CaO/3)),
         P = K2O - (Na2O + CaO),
         Group = factor(Group, labels = c("Peraluminous", "Archean", "Ridge tholeitic", "Amphibole calc-alkaline", "K-rich calc-alkaline", "Alkaline-peralkaline"))) %>% 
  ggplot(aes(x = P, y = Q, color = SubGroup)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_fill_viridis(discrete = TRUE, option = "B") +
  facet_wrap(~Group) +
  theme_light()
```


# Gráfico de barras

```{r}
dados %>%
  dplyr::select(Group, Apatite, La:Lu) %>% 
  mutate(across(La:Lu, as.numeric)) %>% 
  pivot_longer(cols = La:Lu,
               names_to = "variable",
               values_to = "value") %>% 
  ggplot(aes(x = Group, y = value, fill = Group)) +
  stat_summary(geom = "bar") +
  stat_summary() +
  facet_wrap(~variable, scales = "free")
```


# Gráfico de linhas

```{r}
dados %>% 
  dplyr::select(Group, La:Lu) %>% 
  mutate(across(La:Lu, as.numeric)) %>% 
  group_by(Group) %>% 
  summarise(across(La:Lu, .fns = list(mean = ~mean(., na.rm = TRUE),
                                      sd = ~sd(., na.rm = TRUE)),
                   .names = "{.col}_{.fn}")) %>% 
  pivot_longer(cols = La_mean:Lu_sd,
               names_to = "variable",
               values_to = "value") %>% 
  separate(variable,
           into = c("element", "func"),
           sep = "_") %>% 
  pivot_wider(names_from = "func",
              values_from = "value",
              names_glue = "{func}_{.value}") %>% 
  mutate(element = factor(element, levels = c("La", "Ce", "Pr", "Nd", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu"))) %>% 
  ggplot(aes(x = element, y = mean_value, group = Group)) +
  geom_line(aes(color = Group), size = 1.5, alpha = 0.5, lty = 2) +
  geom_point(aes(color = Group), size = 3) +
  geom_errorbar(aes(ymin = mean_value - sd_value, ymax = mean_value + sd_value, color = Group), width = .1) +
  scale_y_log10() +
  labs(title = "Distribuição de elementos terras raras em granitóides",
       subtitle = "",
       color = "Tipos de granitos",
       caption = "Bonin et al. (2020)",
       x = "",
       y = "") +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, face = "italic"))
```



```{r}
setwd("C:/Users/barba/Desktop/ProgramacaoFuncional_Geologia/ProgramacaoFuncional_Geologia/")

#install.packages("readxl")
library(readxl)

dados.ex <- read_excel("dados_santos2009.xlsx") %>% 
  as_tibble()

dados.ex
```


```{r}
dados.ex = read_excel("dados_santos2009.xlsx") %>% 
  rename(distance = `Distance from contact (m)`) %>% 
  mutate(distance = replace_na(distance, "0"),
         litho = case_when(Rock == c("sill", "Sill") ~ "volcanic",
                           Rock == "Black shale" ~ "shale",
                           TRUE ~ "carbonate")) %>% 
  separate(distance,
           into = c("lower", "upper"),
           sep = "–") %>% 
  relocate(litho, upper, lower, .before = Co) %>% 
  mutate(across(upper:Tm, as.double))

dados.ex
```


# Correlação

```{r}
library(corrplot)

dados.ex %>% 
  dplyr::select(lower, Co:Tm) %>% 
  cor() %>% 
  corrplot(method = "ellipse",
           type = "upper")
```


```{r}
library(GGally)

dados.ex %>% 
  dplyr::select(Co:Tm, lower) %>% 
  ggcorr()
```


```{r}
# para calcular correlação
dados.ex %>% 
  dplyr::select(lower, Co:Tm) %>% 
  correlation::correlation()
```







```{r}
dados %>%
  dplyr::select(Tectonic_setting, Apatite, La:Lu) %>% 
  mutate(across(La:Lu, as.numeric)) %>% 
  pivot_longer(cols = La:Lu,
               names_to = "variable",
               values_to = "value") %>% 
  ggplot(aes(x = value, y = Apatite, color = Tectonic_setting)) +
  geom_point(alpha = 0.7) +
  facet_wrap(~Tectonic_setting, scales = "free") +
  geom_smooth(method = "lm", se = FALSE, aes(color = Tectonic_setting)) +
  stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")),
           method = "spearman")
```


# Explorando a relação entre Chumbo e Tório

.pull-left[
```{r plot-label5, eval=FALSE}
dados.ex %>% 
  ggplot(aes(x = lower, y = Th)) +
  geom_point(alpha = 0.7, size = 2) +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "distance to sill (m)",
       y = "Pb (ppm)",
       title = "Título",
       subtitle = "Subtítulo",
       caption = "referência") +
  facet_wrap(~litho, scales = "free")
```
]

.pull-right[
```{r plot-label5-out, ref.label="plot-label5", echo=FALSE}
```
]

# Faça um histograma da variável **last_eruption_year**

```{r}
volcano %>% 
  mutate(last_eruption_year = as.numeric(last_eruption_year)) %>% 
  ggplot(aes(last_eruption_year, fill = evidence_category)) +
  geom_histogram()
```







