---
title: "aula1 - funcionalidades básicas"
output: html_document
editor_options: 
  chunk_output_type: console
---

Como trabalhar no Rstudio
  - Console vs. Rstudio
  - Criando projeto "Intensivão R"
  - Script file
  - Rmarkdown file
      Comentários "##"
      Chunk
      Atalho: Ctrl + Alt + I
      Atalho <- : Alt-
      Knit

# R como calculadora

```{r}
5 + 2 #soma

5 * 2 #multiplicação

8.2 / 2 #divisão

10 - 8 #subtração

5 ** 3 #elevado ao cubo
5 ^ 3

pi

sqrt(81) #raiz quadrada

exp(8) 

log(5)

log10(5)

5 + (3 * 5 / 2) #operações mais elaboradas
```


# Tipos e atribuição de objetos

```{r}
myNumber <- 5 #Camel case - prática de escrever palavras ou frase, onde cada palavra é iniciada com maiúsculas e unidas sem espaços

myNumber

myNumber <- 7

myInteger <- as.integer(myNumber)
myInteger

calculo <- 5 + (3 * 5 / 2)
myNumber * calculo

#myWord = geologia #erro
myWord <- "geologia"
myWord

myFactor <- factor(myWord)
myFactor

mySentence <- "esta é a minha frase"
mySentence

#o R também trabalha com classes lógicas, TRUE or FALSE
#variável boleana (binária, lógica)

myTRUE <- TRUE
4 == 4 #4 é igual a 4?

#qual a estrutura dessas variáveis?
class(myNumber) #variável numérica - qualquer número DECIMAL
class(myInteger) #variável numérica - número INTEIRO
class(myWord) #variável caracter
class(myFactor) #fator
class(mySentence)
class(myTRUE) #variável lógica
```


# Vetores: objetos que contêm uma sequência de elementos/variáveis

```{r}
myNumbers <- c(1, 2, 3, 4, 5) #vetor
myNumbers <- 1:5
myNumbers <- seq(1, 5, by = 1)

myNumbers[myNumbers > 3]
myNumbers[myNumbers >= 3]
myNumbers[myNumbers!= 3]

myWords = c("geoquímica", "estrutural", "estratigrafia") #strings - fator
myWords
myWords[3]
myWords[4]


meuVetor <- c(1, 2, 3, 4, 5)

dp <- sd(meuVetor) #indica o grau de variação de um conjunto de elementos
#quanto menor o desvio padrão, mais homogênea é a amostra
n <- length(meuVetor)

SE <- dp / sqrt(n)
SE #medida de variação de uma média amostral em relação à média da população

#desvio padrão trata de um índice de dispersão da amostra em relação à média
#erro padrão é uma medida que ajuda a avaliar a confiabilidade da média calculada
```


# Matrix - dataframes

```{r}
myMatrix <- matrix(1:6, nrow = 2, ncol = 3) 
myMatrix

y <- seq(1, 10, by = 2)
myMatrix2 <- matrix(y, nrow = 3, ncol = 2)
myMatrix2

#indexação
myMatrix[,1] #coluna 1
myMatrix[1,] #linha 1

#juntar colunas de dois vetores para formar uma matrix
x <- 1:4
y <- 10:13

cbind(x, y) #cbind = Column Bind
#as colunas devem ter o mesmo número de linhas

rbind(x, y) #rbind = Row Bind

matriz <- cbind(x, y)
matriz #matrix matemática

df <- as.data.frame(matriz)
df #banco de dados

class(matriz)
class(df)

str(df)
length(df)

#lista
#matrizes empilhadas
z <- 2:7
myList <- list(x, y, z)
myList[[2]]
myList[[3]][2]

myLists <- list(matriz,z)
myLists[[1]][3,2]
```


# Funções

```{r}
maior = function(parametro1, parametro2) {
  if (parametro1 < parametro2) {
    return(parametro2)
    } else {
      return(parametro1)
      }
}

a = 4
b = 10

maior(parametro1 = b, parametro2 = a)
maior(b, a)
```


